version: '3.5'

services: 

  nginx:
    build: 
      context: nginx
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on: 
       - node

  node:
    build: 
      context: node
    container_name: node
    # Esta configuração fará com que o script de entrada sh espere a porta 3306 no container db estar disponível antes de executar o comando node index.js.
    entrypoint: sh -c "wait-for db:3306 -- node index.js"
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

    

networks: 
  node-network:
    driver: bridge      
